services:
  wynglet-db:
    container_name: wynglet-db
    image: postgres:18-alpine
    environment:
      POSTGRES_DB: wynglet
      POSTGRES_USER: chimbori
      POSTGRES_PASSWORD: chimbori
    ports:
      - 5432:5432
    volumes:
      - /Users/Shared/Unsynced/wynglet-db-data:/var/lib/postgresql
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  wynglet-db-data:
