version: '3'

vars:
  DATABASE_URL: postgresql://chimbori:chimbori@localhost:5432/wynglet
  CONFIG_YML: ../data/wynglet.yml

tasks:
  run:
    desc: Run the binary
    deps: [sqlc, templ, css, fmt, esbuild]
    dir: 'src'
    cmds:
      - go run . -config="{{.CONFIG_YML}}"

  build:
    desc: Build a binary targeting the current OS
    deps: [fmt, esbuild]
    dir: 'src'
    cmds:
      - |-
        CGO_ENABLED=0 \
          go build \
            -trimpath \
            -ldflags="-w -s -X 'wynglet.chimbori.dev/conf.BuildTimestamp=$(TZ="America/Los_Angeles" date +"%Y-%m-%d %H:%M:%S")'"

  test:
    desc: Run all tests
    dir: 'src'
    cmds:
      - go test -count=1 ./...

  testv:
    desc: Run all tests, with verbose output
    dir: 'src'
    cmds:
      - go test -v -count=1 ./...

  fmt:
    desc: Reformat all source files, including templates
    dir: 'src'
    cmds:
      - go mod tidy
      - gofumpt -l -w .
      - goimports -l -w .
      - golangci-lint fmt

  lint:
    desc: Lint sources
    dir: 'src'
    cmds:
      - golangci-lint run

  sqlc:
    desc: Regenerate SQLC-generated sources
    dir: 'src'
    env:
      CGO_CFLAGS: '-DHAVE_STRCHRNUL -mmacosx-version-min=15.4'
      MACOSX_DEPLOYMENT_TARGET: '15.4'
    cmds:
      - sqlc generate

  db:
    desc: Runs PostgreSQL
    cmds:
      - cmd: podman machine start
        ignore_error: true
      - podman compose up --remove-orphans --build

  drop:
    desc: Drop all tables from the database to prepare for an import
    cmds:
      - echo "DROP SCHEMA PUBLIC CASCADE; CREATE SCHEMA PUBLIC;" | psql "{{.DATABASE_URL}}"

  import:
    desc: Imports PostgreSQL from a local file
    deps: [drop]
    cmds:
      - bunzip2 wynglet.sql.bz2 --stdout | psql "{{.DATABASE_URL}}"

  psql:
    desc: Start pSQL to make raw queries to the database
    cmds:
      - psql "{{.DATABASE_URL}}"

  templ:
    desc: Regenerate Templ templates
    dir: 'src'
    cmds:
      - templ generate
      - templ fmt .

  css:
    desc: Regenerate CSS (minified & pretty-printed)
    dir: 'src'
    cmds:
      - tailwindcss --content "**/*.templ" --input embedfs/static/src.css --output embedfs/static/gen.css
      - tailwindcss --content "**/*.templ" --input embedfs/static/src.css --output embedfs/static/gen.min.css --minify
      - tailwindcss --input rating/widget.css  --output rating/widget.min.css  --minify
      - tailwindcss --input rating/success.css --output rating/success.min.css --minify

  esbuild:
    desc: Bundle and minify TypeScript with esbuild
    dir: 'src'
    cmds:
      - esbuild --bundle --target=es2024 dashboard/dashboard.ts --outfile=embedfs/static/dashboard.js
      - esbuild --bundle --target=es2024 dashboard/dashboard.ts --outfile=embedfs/static/dashboard.min.js --minify --minify-identifiers
      - esbuild --bundle --target=es2024 dashboard/ratings.ts   --outfile=embedfs/static/ratings.js
      - esbuild --bundle --target=es2024 dashboard/ratings.ts   --outfile=embedfs/static/ratings.min.js   --minify --minify-identifiers
      - esbuild --bundle --target=es2024 forms/forms.v1.ts      --outfile=embedfs/static/forms.v1.js
      - esbuild --bundle --target=es2024 forms/forms.v1.ts      --outfile=embedfs/static/forms.v1.min.js   --minify --minify-identifiers

  update:
    desc: Update all dependencies
    dir: 'src'
    deps: [fmt]
    cmds:
      - go get -u -t ./...
      - go clean -modcache
      - go mod tidy
      - go fix ./...

  install:
    desc: Build and install the binary
    deps: [fmt]
    dir: 'src'
    cmds:
      - go install .

  docs:
    desc: Build docs using Inkwell
    dir: 'docs'
    cmds:
      - tailwindcss --content "source/**/*.md" --input source/src.css --output source/gen.css
      - tailwindcss --content "source/**/*.md" --input source/src.css --output source/gen.min.css --minify
      - inkwell serve

  setup:
    desc: Setup pre-requisites on a new machine
    dir: 'src'
    env:
      CGO_CFLAGS: '-DHAVE_STRCHRNUL -mmacosx-version-min=15.4'
      MACOSX_DEPLOYMENT_TARGET: '15.4'
    cmds:
      - brew install tailwindcss libpq esbuild
      - brew link libpq --force
      - go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest
      - go install github.com/a-h/templ/cmd/templ@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install mvdan.cc/gofumpt@latest
