// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: domains.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDomain = `-- name: DeleteDomain :exec
DELETE FROM domains
  WHERE domain = $1
`

func (q *Queries) DeleteDomain(ctx context.Context, domain string) error {
	_, err := q.db.Exec(ctx, deleteDomain, domain)
	return err
}

const deleteUnauthorizedStaleDomains = `-- name: DeleteUnauthorizedStaleDomains :one
WITH deleted AS (
  DELETE FROM domains
    WHERE updated_at < NOW() - $1::interval
    AND authorized IS NULL OR authorized = FALSE
    RETURNING _id
  )
  SELECT COUNT(*) from deleted
`

func (q *Queries) DeleteUnauthorizedStaleDomains(ctx context.Context, dollar_1 pgtype.Interval) (int64, error) {
	row := q.db.QueryRow(ctx, deleteUnauthorizedStaleDomains, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertUnauthorizedDomain = `-- name: InsertUnauthorizedDomain :exec
INSERT INTO domains (domain, include_subdomains, authorized, updated_at)
  VALUES ($1, false, NULL, NOW())
  ON CONFLICT(domain) DO NOTHING
`

func (q *Queries) InsertUnauthorizedDomain(ctx context.Context, domain string) error {
	_, err := q.db.Exec(ctx, insertUnauthorizedDomain, domain)
	return err
}

const isAuthorized = `-- name: IsAuthorized :one
SELECT EXISTS (
  SELECT 1 FROM domains
  WHERE (domain ILIKE $1 OR (include_subdomains = true AND $1 ILIKE '%.' || domain))
  AND authorized IS TRUE
)
`

func (q *Queries) IsAuthorized(ctx context.Context, domain string) (bool, error) {
	row := q.db.QueryRow(ctx, isAuthorized, domain)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDomains = `-- name: ListDomains :many
SELECT _id, updated_at, domain, include_subdomains, authorized FROM domains
  ORDER BY authorized ASC, domain
  LIMIT 10000
`

func (q *Queries) ListDomains(ctx context.Context) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomains)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Domain
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.UpdatedAt,
			&i.Domain,
			&i.IncludeSubdomains,
			&i.Authorized,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDomain = `-- name: UpsertDomain :one
INSERT INTO domains (domain, include_subdomains, authorized, updated_at)
  VALUES ($1, $2, $3, NOW())
  ON CONFLICT(domain)
  DO UPDATE SET
    include_subdomains = EXCLUDED.include_subdomains,
    authorized = EXCLUDED.authorized,
    updated_at = NOW()
  RETURNING _id, updated_at, domain, include_subdomains, authorized
`

type UpsertDomainParams struct {
	Domain            string
	IncludeSubdomains *bool
	Authorized        *bool
}

func (q *Queries) UpsertDomain(ctx context.Context, arg UpsertDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, upsertDomain, arg.Domain, arg.IncludeSubdomains, arg.Authorized)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.UpdatedAt,
		&i.Domain,
		&i.IncludeSubdomains,
		&i.Authorized,
	)
	return i, err
}
