// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: forms.sql

package db

import (
	"context"
	"time"
)

const countFormSubmissions = `-- name: CountFormSubmissions :one
SELECT COUNT(*)
  FROM form_submissions
  WHERE form_id = $1
`

func (q *Queries) CountFormSubmissions(ctx context.Context, formID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFormSubmissions, formID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFormSubmission = `-- name: CreateFormSubmission :one
INSERT INTO form_submissions (form_id, domain, ip_address, form_data, is_spam, email_sent_at)
  VALUES ($1, $2, $3, $4, $5, $6)
  RETURNING _id, form_id, submitted_at, domain, ip_address, form_data, is_spam, email_sent_at
`

type CreateFormSubmissionParams struct {
	FormID      string
	Domain      string
	IpAddress   string
	FormData    string
	IsSpam      bool
	EmailSentAt *time.Time
}

func (q *Queries) CreateFormSubmission(ctx context.Context, arg CreateFormSubmissionParams) (FormSubmission, error) {
	row := q.db.QueryRow(ctx, createFormSubmission,
		arg.FormID,
		arg.Domain,
		arg.IpAddress,
		arg.FormData,
		arg.IsSpam,
		arg.EmailSentAt,
	)
	var i FormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.SubmittedAt,
		&i.Domain,
		&i.IpAddress,
		&i.FormData,
		&i.IsSpam,
		&i.EmailSentAt,
	)
	return i, err
}

const deleteFormSubmission = `-- name: DeleteFormSubmission :exec
DELETE FROM form_submissions
  WHERE _id = $1
`

func (q *Queries) DeleteFormSubmission(ctx context.Context, ID int64) error {
	_, err := q.db.Exec(ctx, deleteFormSubmission, ID)
	return err
}

const exportFormSubmissions = `-- name: ExportFormSubmissions :many
SELECT _id, form_id, submitted_at, domain, ip_address, form_data, is_spam, email_sent_at
  FROM form_submissions
  WHERE form_id = $1
  ORDER BY submitted_at DESC
`

func (q *Queries) ExportFormSubmissions(ctx context.Context, formID string) ([]FormSubmission, error) {
	rows, err := q.db.Query(ctx, exportFormSubmissions, formID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormSubmission
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.SubmittedAt,
			&i.Domain,
			&i.IpAddress,
			&i.FormData,
			&i.IsSpam,
			&i.EmailSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFormSubmission = `-- name: GetFormSubmission :one
SELECT _id, form_id, submitted_at, domain, ip_address, form_data, is_spam, email_sent_at
  FROM form_submissions
  WHERE _id = $1
`

func (q *Queries) GetFormSubmission(ctx context.Context, formID int64) (FormSubmission, error) {
	row := q.db.QueryRow(ctx, getFormSubmission, formID)
	var i FormSubmission
	err := row.Scan(
		&i.ID,
		&i.FormID,
		&i.SubmittedAt,
		&i.Domain,
		&i.IpAddress,
		&i.FormData,
		&i.IsSpam,
		&i.EmailSentAt,
	)
	return i, err
}

const listFormSubmissions = `-- name: ListFormSubmissions :many
SELECT _id, form_id, submitted_at, domain, ip_address, form_data, is_spam, email_sent_at
  FROM form_submissions
  WHERE form_id = $3
  ORDER BY submitted_at DESC
  LIMIT $1 OFFSET $2
`

type ListFormSubmissionsParams struct {
	Limit  int32
	Offset int32
	FormID string
}

func (q *Queries) ListFormSubmissions(ctx context.Context, arg ListFormSubmissionsParams) ([]FormSubmission, error) {
	rows, err := q.db.Query(ctx, listFormSubmissions, arg.Limit, arg.Offset, arg.FormID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FormSubmission
	for rows.Next() {
		var i FormSubmission
		if err := rows.Scan(
			&i.ID,
			&i.FormID,
			&i.SubmittedAt,
			&i.Domain,
			&i.IpAddress,
			&i.FormData,
			&i.IsSpam,
			&i.EmailSentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listForms = `-- name: ListForms :many
SELECT form_id, COUNT(*) as count
  FROM form_submissions
  GROUP BY form_id
  ORDER BY form_id
`

type ListFormsRow struct {
	FormID string
	Count  int64
}

func (q *Queries) ListForms(ctx context.Context) ([]ListFormsRow, error) {
	rows, err := q.db.Query(ctx, listForms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFormsRow
	for rows.Next() {
		var i ListFormsRow
		if err := rows.Scan(&i.FormID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
