// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_previews.sql

package db

import (
	"context"
)

const countLinkPreviews = `-- name: CountLinkPreviews :one
SELECT COUNT(*) FROM link_previews
`

func (q *Queries) CountLinkPreviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkPreviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllLinkPreviews = `-- name: DeleteAllLinkPreviews :exec
DELETE FROM link_previews
`

func (q *Queries) DeleteAllLinkPreviews(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllLinkPreviews)
	return err
}

const deleteLinkPreview = `-- name: DeleteLinkPreview :exec
DELETE FROM link_previews
  WHERE url = $1
`

func (q *Queries) DeleteLinkPreview(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, deleteLinkPreview, url)
	return err
}

const getExistingLinkPreviewURLs = `-- name: GetExistingLinkPreviewURLs :many
SELECT url FROM link_previews
  WHERE url = ANY($1::text[])
`

func (q *Queries) GetExistingLinkPreviewURLs(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, getExistingLinkPreviewURLs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var url string
		if err := rows.Scan(&url); err != nil {
			return nil, err
		}
		items = append(items, url)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkPreview = `-- name: GetLinkPreview :one
SELECT _id, url, generated_at, last_accessed_at, access_count, canonical_user_agent FROM link_previews
  WHERE url = $1
`

func (q *Queries) GetLinkPreview(ctx context.Context, url string) (LinkPreview, error) {
	row := q.db.QueryRow(ctx, getLinkPreview, url)
	var i LinkPreview
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.GeneratedAt,
		&i.LastAccessedAt,
		&i.AccessCount,
		&i.CanonicalUserAgent,
	)
	return i, err
}

const getLinkPreviewUserAgentsByDay = `-- name: GetLinkPreviewUserAgentsByDay :many
SELECT
    to_char(date_trunc('day', last_accessed_at), 'YYYY-MM-DD') as day,
    COALESCE(canonical_user_agent, 'Unknown') as canonical_user_agent,
    COALESCE(SUM(COALESCE(access_count, 0)), 0)::bigint as total_accesses
  FROM link_previews
  WHERE last_accessed_at >= NOW() - ($1 * INTERVAL '1 day')
  GROUP BY day, canonical_user_agent
  ORDER BY day DESC, total_accesses DESC
`

type GetLinkPreviewUserAgentsByDayRow struct {
	Day                string
	CanonicalUserAgent string
	TotalAccesses      int64
}

func (q *Queries) GetLinkPreviewUserAgentsByDay(ctx context.Context, dollar_1 interface{}) ([]GetLinkPreviewUserAgentsByDayRow, error) {
	rows, err := q.db.Query(ctx, getLinkPreviewUserAgentsByDay, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkPreviewUserAgentsByDayRow
	for rows.Next() {
		var i GetLinkPreviewUserAgentsByDayRow
		if err := rows.Scan(&i.Day, &i.CanonicalUserAgent, &i.TotalAccesses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkPreviewsByDomain = `-- name: GetLinkPreviewsByDomain :many
SELECT
    COALESCE(SUBSTRING(url FROM 'https?://(?:www\.)?([^/]+)'), url) as domain,
    COALESCE(SUM(COALESCE(access_count, 0)), 0)::bigint as total_accesses
  FROM link_previews
  GROUP BY domain
  ORDER BY total_accesses DESC
`

type GetLinkPreviewsByDomainRow struct {
	Domain        string
	TotalAccesses int64
}

func (q *Queries) GetLinkPreviewsByDomain(ctx context.Context) ([]GetLinkPreviewsByDomainRow, error) {
	rows, err := q.db.Query(ctx, getLinkPreviewsByDomain)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLinkPreviewsByDomainRow
	for rows.Next() {
		var i GetLinkPreviewsByDomainRow
		if err := rows.Scan(&i.Domain, &i.TotalAccesses); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkPreviews = `-- name: ListLinkPreviews :many
SELECT _id, url, generated_at, last_accessed_at, access_count, canonical_user_agent FROM link_previews
  ORDER BY last_accessed_at DESC
`

func (q *Queries) ListLinkPreviews(ctx context.Context) ([]LinkPreview, error) {
	rows, err := q.db.Query(ctx, listLinkPreviews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkPreview
	for rows.Next() {
		var i LinkPreview
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.GeneratedAt,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.CanonicalUserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkPreviewsPaginated = `-- name: ListLinkPreviewsPaginated :many
SELECT _id, url, generated_at, last_accessed_at, access_count, canonical_user_agent FROM link_previews
  ORDER BY last_accessed_at DESC
  LIMIT $1 OFFSET $2
`

type ListLinkPreviewsPaginatedParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLinkPreviewsPaginated(ctx context.Context, arg ListLinkPreviewsPaginatedParams) ([]LinkPreview, error) {
	rows, err := q.db.Query(ctx, listLinkPreviewsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkPreview
	for rows.Next() {
		var i LinkPreview
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.GeneratedAt,
			&i.LastAccessedAt,
			&i.AccessCount,
			&i.CanonicalUserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLinkPreviewAccessed = `-- name: RecordLinkPreviewAccessed :execrows
UPDATE link_previews
  SET last_accessed_at = NOW(),
    access_count = access_count + 1,
    canonical_user_agent = $2
  WHERE url = $1
`

type RecordLinkPreviewAccessedParams struct {
	Url                string
	CanonicalUserAgent *string
}

func (q *Queries) RecordLinkPreviewAccessed(ctx context.Context, arg RecordLinkPreviewAccessedParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordLinkPreviewAccessed, arg.Url, arg.CanonicalUserAgent)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const recordLinkPreviewCreated = `-- name: RecordLinkPreviewCreated :exec
INSERT INTO link_previews (url, canonical_user_agent, generated_at, last_accessed_at, access_count)
  VALUES ($1, $2, NOW(), NOW(), 1)
  ON CONFLICT(url)
  DO UPDATE SET
    generated_at = NOW(),
    last_accessed_at = NOW(),
    access_count = link_previews.access_count + 1,
    canonical_user_agent = $2
  RETURNING _id, url, generated_at, last_accessed_at, access_count, canonical_user_agent
`

type RecordLinkPreviewCreatedParams struct {
	Url                string
	CanonicalUserAgent *string
}

func (q *Queries) RecordLinkPreviewCreated(ctx context.Context, arg RecordLinkPreviewCreatedParams) error {
	_, err := q.db.Exec(ctx, recordLinkPreviewCreated, arg.Url, arg.CanonicalUserAgent)
	return err
}
