// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Domain struct {
	ID                int64
	UpdatedAt         time.Time
	Domain            string
	IncludeSubdomains *bool
	Authorized        *bool
}

type LinkPreview struct {
	ID                 int64
	Url                string
	GeneratedAt        *time.Time
	LastAccessedAt     *time.Time
	AccessCount        *int32
	CanonicalUserAgent *string
}

type Log struct {
	ID            int64
	LoggedAt      time.Time
	RequestMethod *string
	RequestPath   *string
	HttpStatus    *int32
	Url           *string
	Hostname      *string
	Message       *string
	Err           *string
	UserAgent     *string
}

type QrCode struct {
	ID             int64
	Url            string
	GeneratedAt    *time.Time
	LastAccessedAt *time.Time
	AccessCount    *int32
}

type Rating struct {
	ID        int64
	Url       string
	Ui        string
	Rating    int16
	IpAddress string
	RatedAt   time.Time
}
