// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: qr_codes.sql

package db

import (
	"context"
)

const deleteAllQrCodes = `-- name: DeleteAllQrCodes :exec
DELETE FROM qr_codes
`

func (q *Queries) DeleteAllQrCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllQrCodes)
	return err
}

const deleteQrCode = `-- name: DeleteQrCode :exec
DELETE FROM qr_codes
  WHERE url = $1
`

func (q *Queries) DeleteQrCode(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, deleteQrCode, url)
	return err
}

const getQrCode = `-- name: GetQrCode :one
SELECT _id, url, generated_at, last_accessed_at, access_count FROM qr_codes
  WHERE url = $1
`

func (q *Queries) GetQrCode(ctx context.Context, url string) (QrCode, error) {
	row := q.db.QueryRow(ctx, getQrCode, url)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.GeneratedAt,
		&i.LastAccessedAt,
		&i.AccessCount,
	)
	return i, err
}

const listQrCodes = `-- name: ListQrCodes :many
SELECT _id, url, generated_at, last_accessed_at, access_count FROM qr_codes
  ORDER BY last_accessed_at DESC
`

func (q *Queries) ListQrCodes(ctx context.Context) ([]QrCode, error) {
	rows, err := q.db.Query(ctx, listQrCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QrCode
	for rows.Next() {
		var i QrCode
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.GeneratedAt,
			&i.LastAccessedAt,
			&i.AccessCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordQrCodeAccessed = `-- name: RecordQrCodeAccessed :exec
UPDATE qr_codes
  SET last_accessed_at = NOW(),
    access_count = access_count + 1
  WHERE url = $1
`

func (q *Queries) RecordQrCodeAccessed(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, recordQrCodeAccessed, url)
	return err
}

const recordQrCodeCreated = `-- name: RecordQrCodeCreated :exec
INSERT INTO qr_codes (url, generated_at, last_accessed_at, access_count)
  VALUES ($1, NOW(), NOW(), 1)
  ON CONFLICT(url)
  DO UPDATE SET
    generated_at = NOW(),
    last_accessed_at = NOW(),
    access_count = qr_codes.access_count + 1
  RETURNING _id, url, generated_at, last_accessed_at, access_count
`

func (q *Queries) RecordQrCodeCreated(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, recordQrCodeCreated, url)
	return err
}
