// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRatingGroups = `-- name: CountRatingGroups :one
SELECT COUNT(*) FROM (
  SELECT 1 FROM ratings GROUP BY url, ui
) AS grouped
`

func (q *Queries) CountRatingGroups(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countRatingGroups)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldRatings = `-- name: DeleteOldRatings :execrows
DELETE FROM ratings
  WHERE rated_at < NOW() - $1::interval
`

func (q *Queries) DeleteOldRatings(ctx context.Context, dollar_1 pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRatings, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRatingsByDay = `-- name: GetRatingsByDay :many
SELECT
    to_char(date_trunc('day', rated_at), 'YYYY-MM-DD') AS day,
    ui,
    COUNT(*)::bigint AS total_ratings,
    COALESCE(SUM(CASE WHEN rating = 1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_up,
    COALESCE(SUM(CASE WHEN rating = -1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_down,
    COALESCE(AVG(CASE WHEN ui = 'stars' THEN rating::float8 ELSE NULL END), 0)::float8 AS average_stars
  FROM ratings
  WHERE rated_at >= NOW() - ($1 * INTERVAL '1 day')
  GROUP BY day, ui
  ORDER BY day DESC, ui ASC
`

type GetRatingsByDayRow struct {
	Day          string
	Ui           string
	TotalRatings int64
	ThumbsUp     int64
	ThumbsDown   int64
	AverageStars float64
}

func (q *Queries) GetRatingsByDay(ctx context.Context, dollar_1 interface{}) ([]GetRatingsByDayRow, error) {
	rows, err := q.db.Query(ctx, getRatingsByDay, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRatingsByDayRow
	for rows.Next() {
		var i GetRatingsByDayRow
		if err := rows.Scan(
			&i.Day,
			&i.Ui,
			&i.TotalRatings,
			&i.ThumbsUp,
			&i.ThumbsDown,
			&i.AverageStars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRatingsByURL = `-- name: GetRatingsByURL :many
SELECT
    url,
    ui,
    COUNT(*)::bigint AS total_ratings,
    COALESCE(SUM(CASE WHEN rating = 1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_up,
    COALESCE(SUM(CASE WHEN rating = -1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_down,
    COALESCE(AVG(CASE WHEN ui = 'stars' THEN rating::float8 ELSE NULL END), 0)::float8 AS average_stars
  FROM ratings
  GROUP BY url, ui
  ORDER BY total_ratings DESC, url ASC
`

type GetRatingsByURLRow struct {
	Url          string
	Ui           string
	TotalRatings int64
	ThumbsUp     int64
	ThumbsDown   int64
	AverageStars float64
}

func (q *Queries) GetRatingsByURL(ctx context.Context) ([]GetRatingsByURLRow, error) {
	rows, err := q.db.Query(ctx, getRatingsByURL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRatingsByURLRow
	for rows.Next() {
		var i GetRatingsByURLRow
		if err := rows.Scan(
			&i.Url,
			&i.Ui,
			&i.TotalRatings,
			&i.ThumbsUp,
			&i.ThumbsDown,
			&i.AverageStars,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hasRecentRatingByIPForURL = `-- name: HasRecentRatingByIPForURL :one
SELECT EXISTS (
  SELECT 1 FROM ratings
  WHERE url = $1
    AND ip_address = $2
    AND rated_at >= NOW() - INTERVAL '24 hours'
)
`

type HasRecentRatingByIPForURLParams struct {
	Url       string
	IpAddress string
}

func (q *Queries) HasRecentRatingByIPForURL(ctx context.Context, arg HasRecentRatingByIPForURLParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentRatingByIPForURL, arg.Url, arg.IpAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertRating = `-- name: InsertRating :exec
INSERT INTO ratings (url, ui, rating, ip_address, rated_at)
  VALUES ($1, $2, $3, $4, NOW())
`

type InsertRatingParams struct {
	Url       string
	Ui        string
	Rating    int16
	IpAddress string
}

func (q *Queries) InsertRating(ctx context.Context, arg InsertRatingParams) error {
	_, err := q.db.Exec(ctx, insertRating,
		arg.Url,
		arg.Ui,
		arg.Rating,
		arg.IpAddress,
	)
	return err
}

const listRatingGroupsPaginated = `-- name: ListRatingGroupsPaginated :many
SELECT
    url,
    ui,
    COUNT(*)::bigint AS total_ratings,
    COALESCE(SUM(CASE WHEN rating = 1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_up,
    COALESCE(SUM(CASE WHEN rating = -1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_down,
    COALESCE(AVG(CASE WHEN ui = 'stars' THEN rating::float8 ELSE NULL END), 0)::float8 AS average_stars,
    MAX(rated_at) AS last_rated_at
  FROM ratings
  GROUP BY url, ui
  ORDER BY last_rated_at DESC
  LIMIT $1 OFFSET $2
`

type ListRatingGroupsPaginatedParams struct {
	Limit  int32
	Offset int32
}

type ListRatingGroupsPaginatedRow struct {
	Url          string
	Ui           string
	TotalRatings int64
	ThumbsUp     int64
	ThumbsDown   int64
	AverageStars float64
	LastRatedAt  interface{}
}

func (q *Queries) ListRatingGroupsPaginated(ctx context.Context, arg ListRatingGroupsPaginatedParams) ([]ListRatingGroupsPaginatedRow, error) {
	rows, err := q.db.Query(ctx, listRatingGroupsPaginated, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatingGroupsPaginatedRow
	for rows.Next() {
		var i ListRatingGroupsPaginatedRow
		if err := rows.Scan(
			&i.Url,
			&i.Ui,
			&i.TotalRatings,
			&i.ThumbsUp,
			&i.ThumbsDown,
			&i.AverageStars,
			&i.LastRatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
