// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ratings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRatingGroups = `-- name: CountRatingGroups :one
SELECT COUNT(*) FROM (
  SELECT 1 FROM ratings
  WHERE ($1 = 0 OR rated_at >= NOW() - ($1 * INTERVAL '1 day'))
  GROUP BY url, ui
) AS grouped
`

func (q *Queries) CountRatingGroups(ctx context.Context, days interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countRatingGroups, days)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOldRatings = `-- name: DeleteOldRatings :execrows
DELETE FROM ratings
  WHERE rated_at < NOW() - $1::interval
`

func (q *Queries) DeleteOldRatings(ctx context.Context, dollar_1 pgtype.Interval) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldRatings, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasRecentRatingByIPForURL = `-- name: HasRecentRatingByIPForURL :one
SELECT EXISTS (
  SELECT 1 FROM ratings
  WHERE url = $1
    AND ip_address = $2
    AND rated_at >= NOW() - INTERVAL '24 hours'
)
`

type HasRecentRatingByIPForURLParams struct {
	Url       string
	IpAddress string
}

func (q *Queries) HasRecentRatingByIPForURL(ctx context.Context, arg HasRecentRatingByIPForURLParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasRecentRatingByIPForURL, arg.Url, arg.IpAddress)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertRating = `-- name: InsertRating :exec
INSERT INTO ratings (url, ui, rating, ip_address, rated_at)
  VALUES ($1, $2, $3, $4, NOW())
`

type InsertRatingParams struct {
	Url       string
	Ui        string
	Rating    int16
	IpAddress string
}

func (q *Queries) InsertRating(ctx context.Context, arg InsertRatingParams) error {
	_, err := q.db.Exec(ctx, insertRating,
		arg.Url,
		arg.Ui,
		arg.Rating,
		arg.IpAddress,
	)
	return err
}

const listRatingsWithDistribution = `-- name: ListRatingsWithDistribution :many
SELECT
    url,
    ui,
    COUNT(*)::bigint AS total_ratings,
    COALESCE(SUM(CASE WHEN ui = 'thumbs' AND rating = 1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_up,
    COALESCE(SUM(CASE WHEN ui = 'thumbs' AND rating = -1 THEN 1 ELSE 0 END), 0)::bigint AS thumbs_down,
    COALESCE(SUM(CASE WHEN ui = 'stars' AND rating = 1 THEN 1 ELSE 0 END), 0)::bigint AS stars_1,
    COALESCE(SUM(CASE WHEN ui = 'stars' AND rating = 2 THEN 1 ELSE 0 END), 0)::bigint AS stars_2,
    COALESCE(SUM(CASE WHEN ui = 'stars' AND rating = 3 THEN 1 ELSE 0 END), 0)::bigint AS stars_3,
    COALESCE(SUM(CASE WHEN ui = 'stars' AND rating = 4 THEN 1 ELSE 0 END), 0)::bigint AS stars_4,
    COALESCE(SUM(CASE WHEN ui = 'stars' AND rating = 5 THEN 1 ELSE 0 END), 0)::bigint AS stars_5,
    COALESCE(AVG(CASE WHEN ui = 'stars' THEN rating::float8 ELSE NULL END), 0)::float8 AS average_stars,
    CASE
      WHEN ui = 'thumbs' THEN
        SUM(CASE WHEN rating = 1 THEN 1 ELSE 0 END)::float8 / NULLIF(COUNT(*), 0)::float8
      ELSE
        COALESCE(AVG(rating::float8), 0) / 5.0
    END::float8 AS normalized_score
  FROM ratings
  WHERE ($1 = 0 OR rated_at >= NOW() - ($1 * INTERVAL '1 day'))
  GROUP BY url, ui
  ORDER BY normalized_score DESC, url ASC
  LIMIT $3 OFFSET $2
`

type ListRatingsWithDistributionParams struct {
	Days             interface{}
	PaginationOffset int32
	PaginationLimit  int32
}

type ListRatingsWithDistributionRow struct {
	Url             string
	Ui              string
	TotalRatings    int64
	ThumbsUp        int64
	ThumbsDown      int64
	Stars1          int64
	Stars2          int64
	Stars3          int64
	Stars4          int64
	Stars5          int64
	AverageStars    float64
	NormalizedScore float64
}

func (q *Queries) ListRatingsWithDistribution(ctx context.Context, arg ListRatingsWithDistributionParams) ([]ListRatingsWithDistributionRow, error) {
	rows, err := q.db.Query(ctx, listRatingsWithDistribution, arg.Days, arg.PaginationOffset, arg.PaginationLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatingsWithDistributionRow
	for rows.Next() {
		var i ListRatingsWithDistributionRow
		if err := rows.Scan(
			&i.Url,
			&i.Ui,
			&i.TotalRatings,
			&i.ThumbsUp,
			&i.ThumbsDown,
			&i.Stars1,
			&i.Stars2,
			&i.Stars3,
			&i.Stars4,
			&i.Stars5,
			&i.AverageStars,
			&i.NormalizedScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
