name: Create Container Image

on:
  push:
    branches:
      - main
  workflow_dispatch: # Run manually from the Actions tab.

jobs:
  create-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build Image
        run: |
          docker build . --tag ghcr.io/chimbori/wynglet:latest
          docker push ghcr.io/chimbori/wynglet:latest
